apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    role: pictures-queue
    exercise: k8s-skill-lvl-3
spec:
  clusterIP: None
  selector:
    role: pictures-queue
    exercise: k8s-skill-lvl-3
  ports:
    - port: 15672
      name: http
      protocol: TCP
    - port: 5672
      name: amqp
      protocol: TCP
