apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    role: webservice
    exercise: k8s-skill-lvl-3
spec:
  selector:
    role: webservice
    exercise: k8s-skill-lvl-3
  ports:
    - port: 8080
      name: http
      protocol: TCP
